### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,

You should add a README file explaining how to build the extension and how to contribute.

Regards,

### CODE REVIEW

**Comment by Dagger0** [comment]
I added one separately from this pull request. Not that the build instructions are very complicated :)

**Comment by Rudloff** [comment]
Thanks!
You should name the file README.md so GitHub can correctly parse the markdown code :smile:

**Comment by Dagger0** [comment]
Eh... I wanted to stick with plain text. I have a vague, somewhat hard-to-justify dislike of Markdown (I think mainly because Reddit foists it onto you, without any preview functionality, and I can never get the syntax for links right. Is it square brackets for the URL, or is that for the text? Do I put the text first or the URL first? Just let me write HTML!). I can always change it if I actually need something more fancy than plain text.

**Comment by Dagger0** [comment]
Eh... I wanted to stick with plain text. I have a vague, somewhat hard-to-justify dislike of Markdown (I think mainly because Reddit foists it onto you, without any preview functionality, and I can never get the syntax for links right. Is it square brackets for the URL, or is that for the text? Do I put the text first or the URL first? Just let me write HTML!). I can always change it if I actually need something more fancy than plain text.

**Pull request closed without merging**
