### PR TITLE
French locale

### PR DESCRIPTION
**Pull request by Rudloff**
Here is a French translation.
I don't know why, but the strings in *ipvfox.properties* are still displayed in English...

### CODE REVIEW

**Comment by Dagger0** [comment]
It seems to be working fine for me. Looks like you might need to restart Firefox (or at least disable/reenable the extension) for it to pick up on locale changes though.

Also, just to be awkward, I'm going to change &alwaysShow; to "Show URL bar icon even when toolbar button in use" (that phrasing's a little awkward, but it fits into one line and it's a lot better than "Always show the URL bar icon" since it actually reflects what the option does...) Do you want to update that before I pull this?

**Comment by Rudloff** [comment]
You're right, I had to restart the browser first.
I've updated the string.

**Comment by Dagger0** [comment]
Okay, awesome, and thanks for the translation.

I, um, may have found an extra string while I was merging this: a4fea914b783cec3f26e8a13310c547fdaaace1f.

**Comment by Rudloff** [comment]
I have updated the locale: https://github.com/Dagger0/IPvFox/pull/13

**Pull request merged**
